package archival

//
// This file defines the "flat" data format. We use this data format
// as a simpler to process data format used to exchange information
// between the probe and the websteps test helper.
//
// Incidentally, this is also the internal data format that we use
// to store and process measurement results.
//
// This data format is different from the "archival" data format, i.e.,
// the data format used to serialize and submit measurements.
//

import (
	"net/http"
	"time"
)

// FlatDNSLookupEvent contains the results of a DNS lookup.
type FlatDNSLookupEvent struct {
	ALPNs           []string `json:",omitempty"`
	Addresses       []string `json:",omitempty"`
	Domain          string
	Failure         FlatFailure `json:",omitempty"`
	Finished        time.Time
	LookupType      DNSLookupType
	NS              []string `json:",omitempty"`
	ResolverAddress string   `json:",omitempty"`
	ResolverNetwork NetworkType
	Started         time.Time
}

// NewFakeFlatDNSLookupEvent creates a fake FlatDNSLookupEvent using the given values.
func NewFakeFlatDNSLookupEvent(resolverNetwork NetworkType, resolverAddress string,
	lookupType DNSLookupType, domain string, alpns, addresses []string) *FlatDNSLookupEvent {
	now := time.Now()
	return &FlatDNSLookupEvent{
		ALPNs:           alpns,
		Addresses:       addresses,
		Domain:          domain,
		Failure:         "",
		Finished:        now,
		LookupType:      lookupType,
		NS:              []string{},
		ResolverAddress: resolverAddress,
		ResolverNetwork: resolverNetwork,
		Started:         now,
	}
}

// FlatDNSRoundTripEvent contains the result of a DNS round trip.
type FlatDNSRoundTripEvent struct {
	Address  string      `json:",omitempty"`
	Failure  FlatFailure `json:",omitempty"`
	Finished time.Time
	Network  NetworkType
	Query    []byte `json:",omitempty"`
	Reply    []byte `json:",omitempty"`
	Started  time.Time
}

// FlatFailure is the flat data format representation of failure.
type FlatFailure string

// NewFlatFailure constructs a new FlatFailure from an error.
func NewFlatFailure(err error) FlatFailure {
	if err != nil {
		return FlatFailure(err.Error())
	}
	return ""
}

// ToArchivalFailure converts from FlatFailure to ArchivalFailure.
func (ff FlatFailure) ToArchivalFailure() *string {
	if ff != "" {
		s := string(ff)
		return &s
	}
	return nil
}

// IsSuccess returns true if there is no failure, false otherwise.
func (ff FlatFailure) IsSuccess() bool {
	return ff == ""
}

// FlatHTTPRoundTripEvent contains an HTTP round trip.
type FlatHTTPRoundTripEvent struct {
	Failure                 FlatFailure `json:",omitempty"`
	Finished                time.Time
	Method                  string
	RequestHeaders          http.Header
	ResponseBody            []byte      `json:",omitempty"`
	ResponseBodyIsTruncated bool        `json:",omitempty"`
	ResponseBodyLength      int64       `json:",omitempty"`
	ResponseBodyTLSH        string      `json:",omitempty"`
	ResponseHeaders         http.Header `json:",omitempty"`
	Started                 time.Time
	StatusCode              int64 `json:",omitempty"`
	Transport               string
	URL                     string
}

// FlatNetworkEvent contains a network event. This kind of events
// are generated by Dialer, QUICDialer, Conn, QUICConn.
type FlatNetworkEvent struct {
	Count      int64       `json:",omitempty"`
	Failure    FlatFailure `json:",omitempty"`
	Finished   time.Time
	Network    NetworkType `json:",omitempty"`
	Operation  string
	RemoteAddr string `json:",omitempty"`
	Started    time.Time
}

// FlatQUICTLSHandshakeEvent contains a QUIC or TLS handshake event.
type FlatQUICTLSHandshakeEvent struct {
	ALPN            []string    `json:",omitempty"`
	CipherSuite     string      `json:",omitempty"`
	Failure         FlatFailure `json:",omitempty"`
	Finished        time.Time
	NegotiatedProto string `json:",omitempty"`
	Network         NetworkType
	PeerCerts       [][]byte `json:",omitempty"`
	RemoteAddr      string
	SNI             string
	SkipVerify      bool `json:",omitempty"`
	Started         time.Time
	TLSVersion      string `json:",omitempty"`
}
